# docker-compose.yml
version: "3.9"

services:
  autenticador:
    build:
      context: .
      dockerfile: smart_autenticacao/Dockerfile
    container_name: smart-autenticador
    working_dir: /app/smart_autenticacao
    volumes:
      - ./smart_autenticacao:/app/smart_autenticacao
      - ./smart_utils:/app/smart_utils
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
